[webservers]web-1 ansible_host=111.88.254.16 fqdn=fhmcskp5efnifbe1iko6.auto.internalweb-2 ansible_host=93.77.179.253 fqdn=fhm4buqslmarkln6gc14.auto.internal
[databases]main ansible_host=89.169.154.70 fqdn=fhmfk5jahi4sv72j1lgf.auto.internalreplica ansible_host=89.169.136.125 fqdn=fhme9a85vmbr6rmiip9k.auto.internal
[storage]storage ansible_host=89.169.147.237 fqdn=fhmst6dpjv3optqbfih9.auto.internal
